"""In-Memory Sandbox & PII Leak Fuzzer — executes mutation tests safely."""

import importlib.util
import io
import logging
import math
import re
import subprocess
import tempfile
import traceback
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

from pyshield.engine.harvester import generate_mutations
from pyshield.engine.parser import FunctionInfo

# ---------------------------------------------------------------------------
# PII / PHI classifier
# ---------------------------------------------------------------------------

_RE_PII: re.Pattern[str] = re.compile(
    r"ssn|patient_id|credit_card|social_security|dob|date_of_birth",
    re.IGNORECASE,
)

_PII_MOCK_VALUES: dict[str, str] = {
    "ssn": "123-45-6789",
    "patient_id": "PATIENT-00042",
    "credit_card": "4111111111111111",
    "social_security": "987-65-4321",
    "dob": "1990-01-01",
    "date_of_birth": "1990-01-01",
}

# ---------------------------------------------------------------------------
# Circuit-breaker state
# Maps circuit_key → consecutive failure count.
# Module-level so state persists across pipeline invocations.
# ---------------------------------------------------------------------------

_circuit_breaker: dict[str, int] = {}
_CIRCUIT_THRESHOLD: int = 3


# ---------------------------------------------------------------------------
# Public API data structures
# ---------------------------------------------------------------------------


@dataclass
class TestResult:
    """Outcome of a single mutation test execution."""

    function_name: str
    param: str
    value: Any
    passed: bool
    output: str
    error: str | None
    pii_leak_detected: bool = False
    circuit_broken: bool = False


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def reset_circuit_breaker() -> None:
    """Clear all circuit-breaker counters (intended for use in tests)."""
    _circuit_breaker.clear()


def run_mutation_tests(
    filepath: str,
    func_info: FunctionInfo,
    constants: dict[str, object] | None = None,
) -> list[TestResult]:
    """Execute sandboxed mutation tests for *func_info* found in *filepath*.

    For every parameter in the function a set of boundary/edge-case values is
    generated by ``harvester.generate_mutations``.  Each value is injected as
    a keyword argument while remaining parameters receive ``None``.

    The circuit-breaker halts testing for any (function, param, value) triple
    that has accumulated ``_CIRCUIT_THRESHOLD`` consecutive failures, returning
    a ``TestResult`` with ``circuit_broken=True`` and instructing the human
    engineer to intervene.
    """
    path = Path(filepath)
    try:
        source: str = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [
            TestResult(
                function_name=func_info.name,
                param="<read>",
                value=None,
                passed=False,
                output="",
                error=f"Cannot read file: {exc}",
            )
        ]

    results: list[TestResult] = []

    for param in func_info.params:
        mutations: list[object] = generate_mutations(param, constants)

        # Prepend PII seed value so it is always tested first for PII-named params.
        pii_seed: str | None = _get_pii_mock(param)
        if pii_seed is not None:
            mutations = [pii_seed, *mutations]

        for value in mutations:
            cb_key: str = f"{func_info.name}:{param}:{_safe_repr(value)}"

            if _circuit_breaker.get(cb_key, 0) >= _CIRCUIT_THRESHOLD:
                results.append(
                    TestResult(
                        function_name=func_info.name,
                        param=param,
                        value=value,
                        passed=False,
                        output="",
                        error=(
                            "CIRCUIT BREAKER TRIGGERED: This failure has recurred "
                            f"{_CIRCUIT_THRESHOLD}+ consecutive times. "
                            "Human manual review required."
                        ),
                        circuit_broken=True,
                    )
                )
                continue

            result: TestResult = _execute_single_mutation(
                source=source,
                func_info=func_info,
                param=param,
                value=value,
                is_pii=pii_seed is not None and value == pii_seed,
            )
            results.append(result)

            if result.passed:
                _circuit_breaker[cb_key] = 0
            else:
                _circuit_breaker[cb_key] = _circuit_breaker.get(cb_key, 0) + 1

    return results


# ---------------------------------------------------------------------------
# Internal execution helpers
# ---------------------------------------------------------------------------


def _get_pii_mock(param_name: str) -> str | None:
    """Return a realistic PII seed string if *param_name* matches a sensitive category."""
    lower = param_name.lower()
    for key, val in _PII_MOCK_VALUES.items():
        if key in lower:
            return val
    return None


def _safe_repr(value: Any) -> str:
    """Return a syntactically valid Python literal for *value*.

    ``repr()`` produces bare ``nan`` / ``inf`` for special floats, which are
    not valid Python identifiers.  This helper emits ``float('nan')`` etc.
    so the driver script can be parsed and executed without NameErrors.
    """
    if isinstance(value, float):
        if math.isnan(value):
            return "float('nan')"
        if math.isinf(value):
            sign = "" if value > 0 else "-"
            return f"{sign}float('inf')"
    return repr(value)


def _execute_single_mutation(
    source: str,
    func_info: FunctionInfo,
    param: str,
    value: Any,
    is_pii: bool,
) -> TestResult:
    """Run one mutation in an isolated, sandboxed environment.

    Steps:
    1. Build a minimal driver script that imports the target function via
       a ``tempfile.NamedTemporaryFile`` and calls it with the mutation value.
    2. Intercept ``sys.stdout`` and the root ``logging`` handler to capture output.
    3. Mock ``builtins.open`` in write/append/exclusive modes to prevent disk
       mutation; mock ``subprocess.run`` and ``subprocess.Popen`` to prevent
       shell escapes.
    4. Detect PII leaks by checking captured streams for the seed string.
    """
    # Build call kwargs: mutation value for target param, None for all others.
    call_kwargs_repr: dict[str, str] = {
        p: ("None" if p != param else _safe_repr(value))
        for p in func_info.params
    }
    call_kwargs_str = "{" + ", ".join(f"{k!r}: {v}" for k, v in call_kwargs_repr.items()) + "}"

    driver: str = (
        f"{source}\n\n"
        f"_pyshield_result = {func_info.name}(**{call_kwargs_str})\n"
    )

    captured_stdout = io.StringIO()
    captured_log = io.StringIO()
    error_msg: str | None = None
    pii_leak: bool = False

    log_handler = logging.StreamHandler(captured_log)
    root_logger = logging.getLogger()
    root_logger.addHandler(log_handler)

    tmp_path: Path | None = None

    try:
        # Write the driver script to a temp file BEFORE patching open().
        with tempfile.NamedTemporaryFile(
            suffix=".py",
            mode="w",
            delete=False,
            encoding="utf-8",
        ) as tmp:
            tmp.write(driver)
            tmp_path = Path(tmp.name)

        mock_write_open = MagicMock()

        with (
            patch("sys.stdout", captured_stdout),
            patch("builtins.open", side_effect=_safe_open(mock_write_open)),
            patch(
                "subprocess.run",
                return_value=subprocess.CompletedProcess(args=[], returncode=0),
            ),
            patch("subprocess.Popen", MagicMock()),
        ):
            spec = importlib.util.spec_from_file_location(
                "_pyshield_sandbox", str(tmp_path)
            )
            if spec is None or spec.loader is None:
                raise RuntimeError("importlib could not build a module spec.")

            module = importlib.util.module_from_spec(spec)
            try:
                spec.loader.exec_module(module)
            except Exception as exc:
                error_msg = f"{type(exc).__name__}: {exc}\n{traceback.format_exc()}"

        stdout_text: str = captured_stdout.getvalue()
        log_text: str = captured_log.getvalue()

        # PII leak detection: seed value must not appear unmasked in any stream.
        if is_pii and isinstance(value, str) and value:
            if value in stdout_text or value in log_text:
                pii_leak = True
                error_msg = (
                    f"PII LEAK DETECTED: Sensitive value '{value[:6]}…' "
                    "appeared unmasked in captured output."
                )

    except Exception as exc:
        error_msg = f"{type(exc).__name__}: {exc}\n{traceback.format_exc()}"
        stdout_text = captured_stdout.getvalue()
    finally:
        root_logger.removeHandler(log_handler)
        if tmp_path is not None:
            tmp_path.unlink(missing_ok=True)

    return TestResult(
        function_name=func_info.name,
        param=param,
        value=value,
        passed=(error_msg is None and not pii_leak),
        output=captured_stdout.getvalue(),
        error=error_msg,
        pii_leak_detected=pii_leak,
    )


def _safe_open(mock_write: MagicMock) -> Any:
    """Return an ``open()`` replacement that mocks destructive modes (w/a/x).

    Read-mode calls are forwarded to the real built-in ``open`` so that
    ``importlib`` and other internal machinery continue to function correctly.
    """
    _real_open = open

    def _patched_open(
        file: Any,
        mode: str = "r",
        *args: Any,
        **kwargs: Any,
    ) -> Any:
        if any(m in mode for m in ("w", "a", "x")):
            return mock_write(file, mode, *args, **kwargs)
        return _real_open(file, mode, *args, **kwargs)

    return _patched_open
